import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="ui-navbar fixed top-0 left-0 w-full bg-white border-b" style={{ zIndex: 200 }}>
        <div className="ui-toolbar flex items-center w-full h-16">
          <div className="ui-container w-full mx-auto flex-grow px-4">
            <figure className="ui-logo w-10 h-10 bg-gray-300">
              <figcaption className="sr-only">Logo</figcaption>
            </figure>
          </div>
        </div>
      </header>
      <div className="ui-drawer fixed top-0 left-0 h-full min-h-screen">
        <div className="ui-toolbar flex items-center w-full h-16" />
        <div className="ui-sidebar flex bg-white border-r h-full w-[var(--ui-sidebar-width)]">
          sidebar left
        </div>
      </div>
      <div className="ui-drawer fixed top-0 right-0 h-full min-h-screen">
        <div className="ui-toolbar flex items-center w-full h-16" />
        <div className="ui-sidebar flex bg-white border-l h-full w-[var(--ui-sidebar-width)]">
          sidebar right
        </div>
      </div>
      <main className="py-12" style={{ marginLeft: 'var(--ui-sidebar-width)', marginRight: 'var(--ui-sidebar-width)' }}>
        <div className="ui-toolbar flex items-center w-full h-16" />
        <div className="ui-constainer w-full mx-auto flex-grow px-4">
          <article className="bg-white border mx-auto p-8" style={{ width: 768 }}>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad corporis cupiditate dolorem doloremque eius eos, exercitationem fugit, illo ipsum libero modi nihil odit quo quos, reiciendis repellendus soluta sunt vero.
          </article>
        </div>
      </main>
    </>
  )
}
